name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    if: github.repository_owner == 'NTGNguyen'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: 'pip'
          cache-dependency-path: |
            requirements/requirements.txt

      - uses: extractions/setup-just@v2

      - name: Install deps
        run: uv sync --frozen --no-dev

      - name: Generate schemas
        run: just gen-schemas

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: -a --hook-stage manual
