name: Schedule Run
on:
  # schedule:
  #   - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      config: ${{ secrets.config }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install deps
        run: uv sync --all-extras

      - name: Restore config
        if: ${{ env.config != '' }}
        shell: bash
        run: curl -o config.json ${{ env.config }}

      - name: Run
        run: uv run check-phat-nguoi
