name: Schedule Run

# user-config start
on:
  # schedule:
  #   - cron: 0 0 * * 0
  workflow_dispatch:
# user-config end

env:
  TESSERACT_DATASET_URL: 'https://github.com/tesseract-ocr/tessdata/raw/refs/heads/main/eng.traineddata'

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      config: ${{ secrets.config }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: 'pip'
          cache-dependency-path: |
            requirements/requirements.txt

      - uses: extractions/setup-just@v2

      - name: Get required apt packages
        id: get-pkgs
        shell: bash
        run: echo "pkgs=$( tr '\n' ' ' <'./apt_pkgs.txt' )" > "$GITHUB_OUTPUT"

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: ${{ steps.get-pkgs.outputs.pkgs }}
          version: ${{ hashFiles('apt_pkgs.txt') }}
          execute_install_scripts: true

      - name: Download tesseract dataset
        run: |
          sudo mkdir -p /usr/share/tessdata
          cd /usr/share/tessdata
          curl -O ${{ env.TESSERACT_DATASET_URL }}

      - name: Install production deps
        run: uv sync --no-dev

      - name: Restore config
        if: ${{ env.config != '' }}
        shell: bash
        run: curl -o config.json ${{ env.config }}

      - name: Run check phat nguoi
        run: just
